import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ShoppingCartProvider } from "@/components/ShoppingCartContext"; // Import the provider

const inter = Inter({ subsets: ["latin"] });

export const metadata = { // Assuming 'Metadata' type is imported or defined elsewhere
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ShoppingCartProvider> {/* Wrap children with the provider */}
          {children}
        </ShoppingCartProvider>
      </body>
    </html>
  );
}
